# Generated by Django 2.1 on 2023-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='level',
            field=models.CharField(default='无', max_length=100, verbose_name='级别表'),
        ),
    ]
