# Generated by Django 2.1 on 2023-02-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0002_options_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='level',
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default='无', max_length=100, verbose_name='级别表'),
        ),
    ]
