# Generated by Django 2.1 on 2023-02-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0003_auto_20230213_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='npsAnswer',
            field=models.TextField(blank=True, null=True, verbose_name='量表答案'),
        ),
    ]
