# Generated by Django 2.1 on 2023-02-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0004_answer_npsanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rankAnswer',
            field=models.TextField(blank=True, null=True, verbose_name='排序答案'),
        ),
    ]
