# Generated by Django 2.1 on 2023-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0005_answer_rankanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cnt',
            field=models.IntegerField(default=0, null=True, verbose_name='回答次数'),
        ),
    ]
